# Generated by Django 5.2.6 on 2025-11-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.IntegerField(default=1, help_text='Estimated time to complete (hours)'),
        ),
    ]
